- name: Install Apache
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - httpd
  notify: install httpd

- name: Enable Apache
  service:
    name: httpd
    enabled: true
    state: stopped
