- name: Install Apache
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - httpd
    - mod_ssl
  notify: install httpd
  tags:
    - packages
    - apache

- name: Enable modules
  apache2_module:
    state: present
    name: "{{ item }}"
  with_items:
    - ssl
    - headers

- name: Enable Apache
  service:
    name: httpd
    enabled: true
    state: stopped
  tags:
    - apache
