- name: Install Apache
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - httpd
  notify: install httpd

- name: Start Apache
  service:
    name: httpd
    state: started
  become: true

- name: Enable Apache
  command: systemctl enable httpd
  become: true
