- name: Install SCL Repository
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - centos-release-scl

- name: Install PHP 5.5
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - php55
    - php55-php
    - php55-php-gd
    - php55-php-mbstring
    - php55-php-pgsql
