- name: Install PostgreSQL
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - postgresql-server
    - postgresql-contrib
  register: postgresql_installed
  tags:
    - packages

- name: Init PostgreSQL DataBase
  command: postgresql-setup initdb
  become: true
  when: postgresql_installed is defined and postgresql_installed.changed

- name: Start PostgreSQL
  service:
    name: postgresql
    state: started
    enabled: true
  become: true
