- name: Install SCL Repository
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - centos-release-scl

- name: Install PHP 5.5
  yum:
    update_cache: true
    name: "{{ item }}"
    state: present
  with_items:
    - centos-release-scl

