- name: Install NTP
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - ntp
  tags:
    - packages
    - ntp

- name: Enable ntpd
  service:
    name: ntpd
    enabled: true
    state: started
  tags:
    - ntp
