- name: Install EPEL Repository
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - epel-release
  tags:
    - packages
    - certbot

- name: Install Certbot Package
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - python-certbot-apache
  tags:
    - packages
    - certbot

- name: Generate Certbot Script
  template:
    src: certbot-init.sh.j2
    dest: "/usr/local/bin/certbot-{{ owncloud_hostname }}-init.sh"
    owner: root
    group: root
    mode: 0700
  tags:
    - certbot
